### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by danielgomezrico** [codecov/example-java#3]
The example here works but the example in docs is completely different.

![screen shot 2015-11-08 at 1 23 14 am](https://cloud.githubusercontent.com/assets/76348/11019109/5873905c-85b7-11e5-94fd-2f9e66d6a11c.png)

Also, there's support for android?

**Comment by stevepeak** [comment]
Hey @danielgomezrico thank you for noticing this. Both the Bash and Python uploader work. I'll make sure it is consistent in the docs. Thank you!

**Comment by danielgomezrico** [comment]
:+1:
